@startuml

actor "Building Manager" as BM
participant "Phone App" as PA
participant "Robot Management System" as RMS
actor Robot

BM -> PA: Request task

PA -> RMS: Request task

activate RMS
RMS -> RMS: add request to que 
RMS -> RMS: check robot availability

alt robot available
RMS -> Robot: assign task
deactivate RMS
activate Robot
Robot -> Robot: clean room
RMS -> PA: task assigned MSG
deactivate Robot

else robot not available

activate RMS
RMS -> RMS: estimate time
RMS -> PA: Estimated wait time MSG
deactivate RMS

end

PA -> BM: Show Message to Manager

@enduml